import 'package:flutter/material.dart';
import '../models/exercise.dart';
import '../models/lesson.dart';
import '../theme/app_colors.dart';

final List<Unit> banglaToEnglishCurriculum = [
  // ==========================================
  // LEVEL 1: BEGINNER (A1 • প্রারম্ভিক স্তর)
  // ==========================================
  Unit(
    id: 'bn_en_u1',
    unitNumber: 1,
    title: 'সাধারণ সম্ভাষণ ও পরিচিতি',
    description: 'সহজে ইংরেজিতে অভিবাদন ও নিজের পরিচয় দিতে শিখুন',
    themeColor: const Color(0xFF006A4E), // Bangladesh Green
    levelTitle: 'LEVEL 1: BEGINNER (A1 • প্রারম্ভিক স্তর)',
    levelBadge: 'A1',
    lessons: [
      Lesson(
        id: 'bn_en_u1_l1',
        title: 'অভিবাদন ও শুভেচ্ছা',
        description: 'Hello, Good morning, How are you, I am fine',
        icon: Icons.waving_hand_rounded,
        xpReward: 15,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u1_l1_e1',
            prompt: '"হ্যালো / ওহে" এর সঠিক ইংরেজি কোনটি?',
            question: 'হ্যালো',
            options: ['👋 Hello', '🍎 Apple', '💧 Water'],
            correctIndex: 0,
            speakerText: 'Hello',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u1_l1_e2',
            prompt: 'বাক্যটি সাজান: "আমি ভালো আছি"',
            sentenceToTranslate: 'আমি ভালো আছি',
            correctSequence: ['I', 'am', 'fine'],
            tokenBank: ['I', 'am', 'fine', 'you', 'is', 'good', 'he'],
            speakerText: 'I am fine',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u1_l1_e3',
            prompt: 'সঠিক জোড়াগুলো মেলাও:',
            pairs: {
              'হ্যালো': 'Hello',
              'ধন্যবাদ': 'Thank you',
              'শুভ সকাল': 'Good morning',
              'বিদায়': 'Goodbye',
            },
          ),
          const SpeakingExercise(
            id: 'bn_en_u1_l1_e4',
            prompt: 'মাইক্রোফোনে স্পষ্ট উচ্চারণ করুন:',
            targetPhrase: 'Good morning my friend',
            translation: 'শুভ সকাল আমার বন্ধু',
            targetWords: ['Good', 'morning', 'my', 'friend'],
            speakerText: 'Good morning my friend',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u1_l1_e5',
            prompt: 'উপযুক্ত শব্দ দিয়ে শূন্যস্থান পূরণ করুন:',
            prefix: 'Thank ',
            blankAnswer: 'you',
            suffix: ' very much.',
            options: ['you', 'water', 'eat'],
            speakerText: 'Thank you very much.',
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u1_l2',
        title: 'নিজের পরিচয় দেওয়া',
        description: 'My name is, Friend, How are you',
        icon: Icons.person_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u1_l2_e1',
            prompt: '"বন্ধু" শব্দের ইংরেজি অর্থ কী?',
            question: 'বন্ধু',
            options: ['🤝 Friend', '🏠 House', '📖 Book'],
            correctIndex: 0,
            speakerText: 'Friend',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u1_l2_e2',
            prompt: 'ইংরেজি বাক্যটি সাজান: "আমার নাম জন"',
            sentenceToTranslate: 'আমার নাম জন',
            correctSequence: ['My', 'name', 'is', 'John'],
            tokenBank: ['My', 'name', 'is', 'John', 'Your', 'are', 'friend'],
            speakerText: 'My name is John',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u1_l2_e3',
            prompt: 'জোড়া মেলাও:',
            pairs: {
              'বন্ধু': 'Friend',
              'নাম': 'Name',
              'কেমন আছেন': 'How are you',
              'হ্যাঁ': 'Yes',
            },
          ),
          const SpeakingExercise(
            id: 'bn_en_u1_l2_e4',
            prompt: 'বলুন: "Nice to meet you"',
            targetPhrase: 'Nice to meet you',
            translation: 'আপনার সাথে পরিচিত হয়ে ভালো লাগলো',
            targetWords: ['Nice', 'to', 'meet', 'you'],
            speakerText: 'Nice to meet you',
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u1_l3',
        title: 'সাধারণ শিষ্টাচার ও সৌজন্যতা',
        description: 'Please, Excuse me, Sorry, Welcome',
        icon: Icons.favorite_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u1_l3_e1',
            prompt: '"দয়া করে" এর ইংরেজি কোনটি?',
            question: 'দয়া করে',
            options: ['Please', 'Sorry', 'No'],
            correctIndex: 0,
            speakerText: 'Please',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u1_l3_e2',
            prompt: 'বাক্যটি সাজান: "আমাকে মাফ করবেন"',
            sentenceToTranslate: 'আমাকে মাফ করবেন',
            correctSequence: ['Excuse', 'me', 'please'],
            tokenBank: ['Excuse', 'me', 'please', 'Thanks', 'You', 'Hello'],
            speakerText: 'Excuse me please',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u1_l3_e3',
            prompt: 'জোড়া মেলাও:',
            pairs: {
              'দয়া করে': 'Please',
              'দুঃখিত': 'Sorry',
              'মাফ করবেন': 'Excuse me',
              'স্বাগতম': 'Welcome',
            },
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u2',
    unitNumber: 2,
    title: 'দৈনন্দিন খাবার, পানি ও রেস্তোরাঁ',
    description: 'খাবার ও পানীয় চাওয়া এবং রেস্তোরাঁয় অর্ডার করা শিখুন',
    themeColor: AppColors.orange,
    lessons: [
      Lesson(
        id: 'bn_en_u2_l1',
        title: 'খাবার ও পানীয়',
        description: 'Water, Rice, Bread, Tea, Milk',
        icon: Icons.restaurant_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u2_l1_e1',
            prompt: '"পানি" এর ইংরেজি শব্দ নির্বাচন করুন:',
            question: 'পানি',
            options: ['💧 Water', '🥛 Milk', '☕ Tea'],
            correctIndex: 0,
            speakerText: 'Water',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u2_l1_e2',
            prompt: 'বাক্যটি সাজান: "আমি ভাত খাই"',
            sentenceToTranslate: 'আমি ভাত খাই',
            correctSequence: ['I', 'eat', 'rice'],
            tokenBank: ['I', 'eat', 'rice', 'drink', 'bread', 'water'],
            speakerText: 'I eat rice',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u2_l1_e3',
            prompt: 'শব্দগুলো মেলাও:',
            pairs: {
              'পানি': 'Water',
              'ভাত': 'Rice',
              'রুটি': 'Bread',
              'চা': 'Tea',
            },
          ),
          const FillInBlankExercise(
            id: 'bn_en_u2_l1_e4',
            prompt: 'শূন্যস্থান পূরণ করুন:',
            prefix: 'I drink hot ',
            blankAnswer: 'tea',
            suffix: ' in the morning.',
            options: ['tea', 'rice', 'spoon'],
            speakerText: 'I drink hot tea in the morning.',
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u2_l2',
        title: 'রেস্তোরাঁয় অর্ডার করা',
        description: 'Menu, Order, Bill, Delicious',
        icon: Icons.local_dining_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u2_l2_e1',
            prompt: '"বিলটি দিন" বলতে কী বলবেন?',
            question: 'বিলটি দিন',
            options: ['The bill please', 'Good night', 'More water'],
            correctIndex: 0,
            speakerText: 'The bill please',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u2_l2_e2',
            prompt: 'সাজান: "খাবারটি খুব সুস্বাদু"',
            sentenceToTranslate: 'খাবারটি খুব সুস্বাদু',
            correctSequence: ['The', 'food', 'is', 'delicious'],
            tokenBank: ['The', 'food', 'is', 'delicious', 'cold', 'bad', 'tea'],
            speakerText: 'The food is delicious',
          ),
          const SpeakingExercise(
            id: 'bn_en_u2_l2_e3',
            prompt: 'রেস্তোরাঁয় বলুন: "Can I see the menu please?"',
            targetPhrase: 'Can I see the menu please',
            translation: 'আমি কি মেনুটা দেখতে পারি?',
            targetWords: ['Can', 'I', 'see', 'the', 'menu', 'please'],
            speakerText: 'Can I see the menu please',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u3',
    unitNumber: 3,
    title: 'পরিবার ও আত্মীয়স্বজন',
    description: 'বাবা-মা, ভাই-বোন ও পরিবার নিয়ে ইংরেজিতে কথা বলুন',
    themeColor: AppColors.purple,
    lessons: [
      Lesson(
        id: 'bn_en_u3_l1',
        title: 'পরিবারের সদস্য',
        description: 'Father, Mother, Brother, Sister',
        icon: Icons.people_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u3_l1_e1',
            prompt: '"মা" এর ইংরেজি কোনটি?',
            question: 'মা',
            options: ['Mother', 'Father', 'Sister'],
            correctIndex: 0,
            speakerText: 'Mother',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u3_l1_e2',
            prompt: 'সাজান: "তিনি আমার বড় ভাই"',
            sentenceToTranslate: 'তিনি আমার বড় ভাই',
            correctSequence: ['He', 'is', 'my', 'brother'],
            tokenBank: ['He', 'is', 'my', 'brother', 'She', 'sister', 'father'],
            speakerText: 'He is my brother',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u3_l1_e3',
            prompt: 'পারিবারিক সম্পর্ক মেলাও:',
            pairs: {
              'বাবা': 'Father',
              'মা': 'Mother',
              'ভাই': 'Brother',
              'বোন': 'Sister',
            },
          ),
          const FillInBlankExercise(
            id: 'bn_en_u3_l1_e4',
            prompt: 'শূন্যস্থান পূরণ করুন:',
            prefix: 'I love my ',
            blankAnswer: 'family',
            suffix: ' very much.',
            options: ['family', 'car', 'pen'],
            speakerText: 'I love my family very much.',
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u3_l2',
        title: 'পরিবারের বর্ণনা',
        description: 'Parents, Children, Kind, Home',
        icon: Icons.home_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u3_l2_e1',
            prompt: '"পিতা-মাতা" শব্দের ইংরেজি কী?',
            question: 'পিতা-মাতা',
            options: ['Parents', 'Friends', 'Teachers'],
            correctIndex: 0,
            speakerText: 'Parents',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u3_l2_e2',
            prompt: 'সাজান: "আমার একটি ছোট পরিবার আছে"',
            sentenceToTranslate: 'আমার একটি ছোট পরিবার আছে',
            correctSequence: ['I', 'have', 'a', 'small', 'family'],
            tokenBank: ['I', 'have', 'a', 'small', 'family', 'big', 'are'],
            speakerText: 'I have a small family',
          ),
          const SpeakingExercise(
            id: 'bn_en_u3_l2_e3',
            prompt: 'বলুন: "My parents live in Dhaka"',
            targetPhrase: 'My parents live in Dhaka',
            translation: 'আমার পিতা-মাতা ঢাকায় থাকেন',
            targetWords: ['My', 'parents', 'live', 'in', 'Dhaka'],
            speakerText: 'My parents live in Dhaka',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u4',
    unitNumber: 4,
    title: 'সংখ্যা, সময় ও ক্যালেন্ডার',
    description: 'ইংরেজি সংখ্যা ১ থেকে ২০, সপ্তাহের দিন ও সময় বলা শিখুন',
    themeColor: AppColors.blue,
    lessons: [
      Lesson(
        id: 'bn_en_u4_l1',
        title: 'সংখ্যা গণনা (১-২০)',
        description: 'One, Two, Three, Ten, Twenty',
        icon: Icons.pin_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u4_l1_e1',
            prompt: '"দশ" এর ইংরেজি কোনটি?',
            question: 'দশ (১০)',
            options: ['Ten', 'Two', 'Seven'],
            correctIndex: 0,
            speakerText: 'Ten',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u4_l1_e2',
            prompt: 'সাজান: "আমার দুটি বই আছে"',
            sentenceToTranslate: 'আমার দুটি বই আছে',
            correctSequence: ['I', 'have', 'two', 'books'],
            tokenBank: ['I', 'have', 'two', 'books', 'one', 'three', 'pen'],
            speakerText: 'I have two books',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u4_l1_e3',
            prompt: 'সংখ্যাগুলো মেলাও:',
            pairs: {
              'এক': 'One',
              'পাঁচ': 'Five',
              'দশ': 'Ten',
              'বিশ': 'Twenty',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u4_l2',
        title: 'সময় ও সপ্তাহের দিন',
        description: 'Time, Monday, Friday, Morning, Night',
        icon: Icons.access_time_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u4_l2_e1',
            prompt: '"কয়টা বাজে?" এর ইংরেজি প্রশ্ন কী?',
            question: 'কয়টা বাজে?',
            options: ['What time is it?', 'Where are you?', 'Who is that?'],
            correctIndex: 0,
            speakerText: 'What time is it?',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u4_l2_e2',
            prompt: 'সাজান: "আজ সোমবার"',
            sentenceToTranslate: 'আজ সোমবার',
            correctSequence: ['Today', 'is', 'Monday'],
            tokenBank: ['Today', 'is', 'Monday', 'Sunday', 'was', 'day'],
            speakerText: 'Today is Monday',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u4_l2_e3',
            prompt: 'সঠিক দিন বসান:',
            prefix: 'Friday is the ',
            blankAnswer: 'weekend',
            suffix: ' in Bangladesh.',
            options: ['weekend', 'night', 'morning'],
            speakerText: 'Friday is the weekend in Bangladesh.',
          ),
        ],
      ),
    ],
  ),

  // ==========================================
  // LEVEL 2: ELEMENTARY (A2 • প্রাথমিক স্তর)
  // ==========================================
  Unit(
    id: 'bn_en_u5',
    unitNumber: 5,
    title: 'বাসস্থান ও দৈনন্দিন রুটিন',
    description: 'ঘরের বিভিন্ন জিনিস এবং সকাল থেকে রাতের রুটিন প্রকাশ করুন',
    themeColor: AppColors.greenDark,
    levelTitle: 'LEVEL 2: ELEMENTARY (A2 • প্রাথমিক স্তর)',
    levelBadge: 'A2',
    lessons: [
      Lesson(
        id: 'bn_en_u5_l1',
        title: 'ঘরের জিনিসপত্র',
        description: 'Bedroom, Kitchen, Table, Chair',
        icon: Icons.chair_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u5_l1_e1',
            prompt: '"রান্নাঘর" এর ইংরেজি শব্দ কোনটি?',
            question: 'রান্নাঘর',
            options: ['Kitchen', 'Bedroom', 'Garden'],
            correctIndex: 0,
            speakerText: 'Kitchen',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u5_l1_e2',
            prompt: 'সাজান: "বইটি টেবিলের উপরে আছে"',
            sentenceToTranslate: 'বইটি টেবিলের উপরে আছে',
            correctSequence: ['The', 'book', 'is', 'on', 'the', 'table'],
            tokenBank: ['The', 'book', 'is', 'on', 'the', 'table', 'under', 'chair'],
            speakerText: 'The book is on the table',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u5_l1_e3',
            prompt: 'ঘরের আসবাবপত্র মেলাও:',
            pairs: {
              'চেয়ার': 'Chair',
              'টেবিল': 'Table',
              'দরজা': 'Door',
              'জানালা': 'Window',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u5_l2',
        title: 'দৈনন্দিন রুটিন',
        description: 'Wake up, Brush teeth, Breakfast, Sleep',
        icon: Icons.alarm_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u5_l2_e1',
            prompt: '"আমি সকাল ৭টায় ঘুম থেকে উঠি"',
            question: 'আমি সকালে ঘুম থেকে উঠি',
            options: ['I wake up early', 'I sleep late', 'I eat lunch'],
            correctIndex: 0,
            speakerText: 'I wake up early',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u5_l2_e2',
            prompt: 'সাজান: "আমি স্কুলে যাই"',
            sentenceToTranslate: 'আমি স্কুলে যাই',
            correctSequence: ['I', 'go', 'to', 'school'],
            tokenBank: ['I', 'go', 'to', 'school', 'goes', 'went', 'market'],
            speakerText: 'I go to school',
          ),
          const SpeakingExercise(
            id: 'bn_en_u5_l2_e3',
            prompt: 'উচ্চারণ করুন: "I brush my teeth every morning"',
            targetPhrase: 'I brush my teeth every morning',
            translation: 'আমি প্রতিদিন সকালে দাঁত মাজি',
            targetWords: ['I', 'brush', 'my', 'teeth', 'every', 'morning'],
            speakerText: 'I brush my teeth every morning',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u6',
    unitNumber: 6,
    title: 'কেনাকাটা, পোশাক ও মূল্য',
    description: 'দোকানে গিয়ে কেনাকাটা, পোশাকের সাইজ ও দাম নিয়ে কথা বলুন',
    themeColor: const Color(0xFFE91E63), // Pink
    lessons: [
      Lesson(
        id: 'bn_en_u6_l1',
        title: 'পোশাক ও রং',
        description: 'Shirt, Pants, Shoes, Red, Blue, Black',
        icon: Icons.checkroom_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u6_l1_e1',
            prompt: '"জুতা" শব্দের ইংরেজি কোনটি?',
            question: 'জুতা',
            options: ['Shoes', 'Shirt', 'Hat'],
            correctIndex: 0,
            speakerText: 'Shoes',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u6_l1_e2',
            prompt: 'সাজান: "আমি একটি লাল শার্ট চাই"',
            sentenceToTranslate: 'আমি একটি লাল শার্ট চাই',
            correctSequence: ['I', 'want', 'a', 'red', 'shirt'],
            tokenBank: ['I', 'want', 'a', 'red', 'shirt', 'blue', 'shoes'],
            speakerText: 'I want a red shirt',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u6_l1_e3',
            prompt: 'রং ও পোশাক মেলাও:',
            pairs: {
              'লাল': 'Red',
              'নীল': 'Blue',
              'কালো': 'Black',
              'সাদা': 'White',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u6_l2',
        title: 'দাম ও লেনদেন',
        description: 'How much, Expensive, Cheap, Cash, Card',
        icon: Icons.shopping_cart_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u6_l2_e1',
            prompt: '"এটার দাম কত?" ইংরেজিতে কীভাবে বলবেন?',
            question: 'এটার দাম কত?',
            options: ['How much is this?', 'Where is this?', 'Who is this?'],
            correctIndex: 0,
            speakerText: 'How much is this?',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u6_l2_e2',
            prompt: 'সাজান: "আমি কার্ড দিয়ে দিতে পারি?"',
            sentenceToTranslate: 'আমি কি কার্ডে পরিশোধ করতে পারি?',
            correctSequence: ['Can', 'I', 'pay', 'by', 'card?'],
            tokenBank: ['Can', 'I', 'pay', 'by', 'card?', 'cash', 'money'],
            speakerText: 'Can I pay by card?',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u6_l2_e3',
            prompt: 'শূন্যস্থান পূরণ করুন:',
            prefix: 'This watch is very ',
            blankAnswer: 'expensive',
            suffix: ', but beautiful.',
            options: ['expensive', 'tasty', 'water'],
            speakerText: 'This watch is very expensive, but beautiful.',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u7',
    unitNumber: 7,
    title: 'দিকনির্দেশনা ও যাতায়াত',
    description: 'রাস্তায় পথ চাওয়া, বাস-ট্রেন ও গণপরিবহনে কথা বলা শিখুন',
    themeColor: const Color(0xFF00897B), // Teal
    lessons: [
      Lesson(
        id: 'bn_en_u7_l1',
        title: 'পথ ও দিক খোঁজা',
        description: 'Left, Right, Straight, Near, Far',
        icon: Icons.navigation_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u7_l1_e1',
            prompt: '"বামে ঘুরুন" এর ইংরেজি কোনটি?',
            question: 'বামে ঘুরুন',
            options: ['Turn left', 'Turn right', 'Go back'],
            correctIndex: 0,
            speakerText: 'Turn left',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u7_l1_e2',
            prompt: 'সাজান: "সোজা এগিয়ে যান"',
            sentenceToTranslate: 'সোজা এগিয়ে যান',
            correctSequence: ['Go', 'straight', 'ahead'],
            tokenBank: ['Go', 'straight', 'ahead', 'left', 'stop', 'back'],
            speakerText: 'Go straight ahead',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u7_l1_e3',
            prompt: 'দিকনির্দেশনা মেলাও:',
            pairs: {
              'ডান': 'Right',
              'বাম': 'Left',
              'সোজা': 'Straight',
              'কাছে': 'Near',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u7_l2',
        title: 'যানবাহন ও টিকিট',
        description: 'Bus stop, Train station, Ticket, Airport',
        icon: Icons.directions_bus_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u7_l2_e1',
            prompt: '"বাস স্টপটি কোথায়?" ইংরেজিতে বলুন:',
            question: 'বাস স্টপটি কোথায়?',
            options: ['Where is the bus stop?', 'When is the bus?', 'Who is on the bus?'],
            correctIndex: 0,
            speakerText: 'Where is the bus stop?',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u7_l2_e2',
            prompt: 'সাজান: "আমাকে একটি টিকিট দিন"',
            sentenceToTranslate: 'আমাকে একটি টিকিট দিন',
            correctSequence: ['One', 'ticket', 'please'],
            tokenBank: ['One', 'ticket', 'please', 'two', 'bus', 'train'],
            speakerText: 'One ticket please',
          ),
          const SpeakingExercise(
            id: 'bn_en_u7_l2_e3',
            prompt: 'বলুন: "How far is the airport from here?"',
            targetPhrase: 'How far is the airport from here',
            translation: 'এখান থেকে বিমানবন্দর কতদূর?',
            targetWords: ['How', 'far', 'is', 'the', 'airport', 'from', 'here'],
            speakerText: 'How far is the airport from here',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u8',
    unitNumber: 8,
    title: 'অনুভূতি, শরীর ও স্বাস্থ্য',
    description: 'শারীরিক অনুভূতি, অসুস্থতা প্রকাশ ও ডাক্তারের সাথে কথা বলুন',
    themeColor: const Color(0xFFD32F2F), // Medical Crimson
    lessons: [
      Lesson(
        id: 'bn_en_u8_l1',
        title: 'শরীরের অঙ্গ ও অসুস্থতা',
        description: 'Headache, Fever, Cold, Stomach, Pain',
        icon: Icons.health_and_safety_rounded,
        xpReward: 20,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u8_l1_e1',
            prompt: '"মাথাব্যথা" এর ইংরেজি কী?',
            question: 'মাথাব্যথা',
            options: ['Headache', 'Fever', 'Cough'],
            correctIndex: 0,
            speakerText: 'Headache',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u8_l1_e2',
            prompt: 'সাজান: "আমার জ্বর এসেছে"',
            sentenceToTranslate: 'আমার জ্বর এসেছে',
            correctSequence: ['I', 'have', 'a', 'fever'],
            tokenBank: ['I', 'have', 'a', 'fever', 'has', 'cold', 'head'],
            speakerText: 'I have a fever',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u8_l1_e3',
            prompt: 'শারীরিক লক্ষণ মেলাও:',
            pairs: {
              'জ্বর': 'Fever',
              'কাশি': 'Cough',
              'মাথা': 'Head',
              'হাত': 'Hand',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u8_l2',
        title: 'ডাক্তারের কাছে পরামর্শ',
        description: 'Medicine, Doctor, Prescription, Rest',
        icon: Icons.medical_services_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u8_l2_e1',
            prompt: '"এই ওষুধটি দিনে দুইবার খাবেন"',
            question: 'ওষুধটি দিনে দুইবার খান',
            options: ['Take this medicine twice a day', 'Drink cold juice', 'Walk fast'],
            correctIndex: 0,
            speakerText: 'Take this medicine twice a day',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u8_l2_e2',
            prompt: 'সাজান: "আপনার দ্রুত সুস্থতা কামনা করি"',
            sentenceToTranslate: 'দ্রুত সুস্থ হয়ে উঠুন',
            correctSequence: ['Get', 'well', 'soon'],
            tokenBank: ['Get', 'well', 'soon', 'happy', 'better', 'take'],
            speakerText: 'Get well soon',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u8_l2_e3',
            prompt: 'শূন্যস্থান পূরণ করুন:',
            prefix: 'You need to take plenty of ',
            blankAnswer: 'rest',
            suffix: ' and drink water.',
            options: ['rest', 'shirt', 'car'],
            speakerText: 'You need to take plenty of rest and drink water.',
          ),
        ],
      ),
    ],
  ),

  // ==========================================
  // LEVEL 3: INTERMEDIATE (B1 • মধ্যবর্তী স্তর)
  // ==========================================
  Unit(
    id: 'bn_en_u9',
    unitNumber: 9,
    title: 'অতীত কাল ও জীবনের গল্প',
    description: 'অতীতের ঘটনা, স্মৃতিচারণ ও গল্প বলা শিখুন (Past Tense Mastery)',
    themeColor: AppColors.blueDark,
    levelTitle: 'LEVEL 3: INTERMEDIATE (B1 • মধ্যবর্তী স্তর)',
    levelBadge: 'B1',
    lessons: [
      Lesson(
        id: 'bn_en_u9_l1',
        title: 'গতকাল কী ঘটেছিল?',
        description: 'Went, Saw, Ate, Visited, Yesterday',
        icon: Icons.history_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u9_l1_e1',
            prompt: '"Go" এর অতীত রূপ (Past form) কোনটি?',
            question: 'Go এর Past Form',
            options: ['Went', 'Gone', 'Going'],
            correctIndex: 0,
            speakerText: 'Went',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u9_l1_e2',
            prompt: 'সাজান: "গতকাল আমি সিনেমা দেখেছি"',
            sentenceToTranslate: 'গতকাল আমি একটি সিনেমা দেখেছি',
            correctSequence: ['Yesterday', 'I', 'watched', 'a', 'movie'],
            tokenBank: ['Yesterday', 'I', 'watched', 'a', 'movie', 'see', 'watch'],
            speakerText: 'Yesterday I watched a movie',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u9_l1_e3',
            prompt: 'Present ও Past Tense মেলাও:',
            pairs: {
              'Eat (খাওয়া)': 'Ate',
              'See (দেখা)': 'Saw',
              'Come (আসা)': 'Came',
              'Buy (কেনা)': 'Bought',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u9_l2',
        title: 'শৈশবের সোনালী স্মৃতি',
        description: 'When I was young, Used to, Memories',
        icon: Icons.auto_stories_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u9_l2_e1',
            prompt: '"আমি ছোটবেলায় ফুটবল খেলতাম"',
            question: 'আমি ছোটবেলায় খেলতাম',
            options: ['I used to play football', 'I will play football', 'I playing football'],
            correctIndex: 0,
            speakerText: 'I used to play football',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u9_l2_e2',
            prompt: 'সাজান: "আমরা গ্রামে থাকতাম"',
            sentenceToTranslate: 'আমরা গ্রামে বাস করতাম',
            correctSequence: ['We', 'lived', 'in', 'a', 'village'],
            tokenBank: ['We', 'lived', 'in', 'a', 'village', 'live', 'city'],
            speakerText: 'We lived in a village',
          ),
          const SpeakingExercise(
            id: 'bn_en_u9_l2_e3',
            prompt: 'উচ্চারণ করুন: "Those were the happiest days of my life"',
            targetPhrase: 'Those were the happiest days of my life',
            translation: 'সেগুলো ছিল আমার জীবনের সবচেয়ে সুখের দিন',
            targetWords: ['Those', 'were', 'the', 'happiest', 'days', 'of', 'my', 'life'],
            speakerText: 'Those were the happiest days of my life',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u10',
    unitNumber: 10,
    title: 'ভবিষ্যৎ পরিকল্পনা ও স্বপ্ন',
    description: 'আগামীর স্বপ্ন, পরিকল্পনা ও ইচ্ছা প্রকাশ করা শিখুন (Future Tense)',
    themeColor: AppColors.purpleDark,
    lessons: [
      Lesson(
        id: 'bn_en_u10_l1',
        title: 'আগামীকালের পরিকল্পনা',
        description: 'Will, Going to, Tomorrow, Next week',
        icon: Icons.rocket_launch_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u10_l1_e1',
            prompt: '"আমি আগামীকাল চট্টগ্রাম যাব"',
            question: 'আমি আগামীকাল যাব',
            options: ['I will go to Chittagong tomorrow', 'I went to Chittagong', 'I go now'],
            correctIndex: 0,
            speakerText: 'I will go to Chittagong tomorrow',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u10_l1_e2',
            prompt: 'সাজান: "আমরা একটি নতুন বাড়ি কিনব"',
            sentenceToTranslate: 'আমরা একটি নতুন বাড়ি কিনব',
            correctSequence: ['We', 'are', 'going', 'to', 'buy', 'a', 'house'],
            tokenBank: ['We', 'are', 'going', 'to', 'buy', 'a', 'house', 'bought', 'will'],
            speakerText: 'We are going to buy a house',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u10_l1_e3',
            prompt: 'ভবিষ্যৎ অভিব্যক্তি মেলাও:',
            pairs: {
              'আগামীকাল': 'Tomorrow',
              'আগামী সপ্তাহে': 'Next week',
              'ভবিষ্যতে': 'In the future',
              'শীঘ্রই': 'Soon',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u10_l2',
        title: 'জীবনের লক্ষ্য ও ক্যারিয়ার',
        description: 'Career, Ambition, Engineer, Achieve',
        icon: Icons.workspace_premium_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u10_l2_e1',
            prompt: '"আমার স্বপ্ন একজন সফল মানুষ হওয়া"',
            question: 'আমার স্বপ্ন',
            options: ['My dream is to be successful', 'I am sleeping', 'I have work'],
            correctIndex: 0,
            speakerText: 'My dream is to be successful',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u10_l2_e2',
            prompt: 'সাজান: "আমি সফটওয়্যার ইঞ্জিনিয়ার হতে চাই"',
            sentenceToTranslate: 'আমি একজন সফটওয়্যার ইঞ্জিনিয়ার হতে চাই',
            correctSequence: ['I', 'want', 'to', 'become', 'a', 'software', 'engineer'],
            tokenBank: ['I', 'want', 'to', 'become', 'a', 'software', 'engineer', 'will', 'is'],
            speakerText: 'I want to become a software engineer',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u10_l2_e3',
            prompt: 'উপযুক্ত শব্দ বসান:',
            prefix: 'If you work hard, you will ',
            blankAnswer: 'succeed',
            suffix: ' in your goals.',
            options: ['succeed', 'sleep', 'break'],
            speakerText: 'If you work hard, you will succeed in your goals.',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u11',
    unitNumber: 11,
    title: 'শখ, খেলাধুলা ও প্রযুক্তি',
    description: 'ক্রিকেট, গান, স্মার্টফোন ও সোশ্যাল মিডিয়া নিয়ে আলোচনা',
    themeColor: AppColors.green,
    lessons: [
      Lesson(
        id: 'bn_en_u11_l1',
        title: 'প্রিয় খেলা ও বিনোদন',
        description: 'Cricket, Football, Music, Movies, Hobbies',
        icon: Icons.sports_cricket_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u11_l1_e1',
            prompt: '"ক্রিকেট আমাদের প্রিয় খেলা"',
            question: 'ক্রিকেট আমাদের প্রিয় খেলা',
            options: ['Cricket is our favorite sport', 'Cricket is boring', 'I do not play cricket'],
            correctIndex: 0,
            speakerText: 'Cricket is our favorite sport',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u11_l1_e2',
            prompt: 'সাজান: "আমি অবসর সময়ে গান শুনি"',
            sentenceToTranslate: 'আমি গান শুনতে ভালোবাসি',
            correctSequence: ['I', 'love', 'listening', 'to', 'music'],
            tokenBank: ['I', 'love', 'listening', 'to', 'music', 'listen', 'play'],
            speakerText: 'I love listening to music',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u11_l1_e3',
            prompt: 'শখের বিষয়গুলো মেলাও:',
            pairs: {
              'গান শোনা': 'Listening to music',
              'বই পড়া': 'Reading books',
              'ছবি আঁকা': 'Drawing pictures',
              'ভ্রমণ করা': 'Traveling',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u11_l2',
        title: 'প্রযুক্তি ও সোশ্যাল মিডিয়া',
        description: 'Smartphone, Internet, Download, Share, Message',
        icon: Icons.phone_iphone_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u11_l2_e1',
            prompt: '"অ্যাপটি ডাউনলোড করুন" এর ইংরেজি কোনটি?',
            question: 'অ্যাপটি ডাউনলোড করুন',
            options: ['Download the app', 'Delete the file', 'Close the phone'],
            correctIndex: 0,
            speakerText: 'Download the app',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u11_l2_e2',
            prompt: 'সাজান: "আমাকে একটি ইমেইল পাঠাও"',
            sentenceToTranslate: 'আমাকে একটি ইমেইল পাঠাও',
            correctSequence: ['Send', 'me', 'an', 'email'],
            tokenBank: ['Send', 'me', 'an', 'email', 'a', 'call', 'text'],
            speakerText: 'Send me an email',
          ),
          const SpeakingExercise(
            id: 'bn_en_u11_l2_e3',
            prompt: 'বলুন: "Can you share the file with me?"',
            targetPhrase: 'Can you share the file with me',
            translation: 'তুমি কি ফাইলটি আমার সাথে শেয়ার করতে পারবে?',
            targetWords: ['Can', 'you', 'share', 'the', 'file', 'with', 'me'],
            speakerText: 'Can you share the file with me',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u12',
    unitNumber: 12,
    title: 'আবহাওয়া, ঋতু ও প্রকৃতি',
    description: 'বর্ষাকাল, রোদবৃষ্টি, ঋতু পরিবর্তন ও জলবায়ু নিয়ে কথা বলুন',
    themeColor: AppColors.blue,
    lessons: [
      Lesson(
        id: 'bn_en_u12_l1',
        title: 'ঋতু ও প্রকৃতি',
        description: 'Rainy season, Summer, Winter, Monsoon',
        icon: Icons.wb_sunny_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u12_l1_e1',
            prompt: '"বর্ষাকাল" এর ইংরেজি কী?',
            question: 'বর্ষাকাল',
            options: ['Rainy season', 'Winter season', 'Spring season'],
            correctIndex: 0,
            speakerText: 'Rainy season',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u12_l1_e2',
            prompt: 'সাজান: "বাইরে মুষলধারে বৃষ্টি হচ্ছে"',
            sentenceToTranslate: 'বাইরে বৃষ্টি হচ্ছে',
            correctSequence: ['It', 'is', 'raining', 'outside'],
            tokenBank: ['It', 'is', 'raining', 'outside', 'was', 'sun', 'cold'],
            speakerText: 'It is raining outside',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u12_l1_e3',
            prompt: 'ঋতুর নাম মেলাও:',
            pairs: {
              'গ্রীষ্মকাল': 'Summer',
              'শীতকাল': 'Winter',
              'বসন্তকাল': 'Spring',
              'শরৎকাল': 'Autumn',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u12_l2',
        title: 'আবহাওয়া পূর্বাভাস',
        description: 'Forecast, Umbrella, Storm, Sunny, Cold',
        icon: Icons.cloud_rounded,
        xpReward: 25,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u12_l2_e1',
            prompt: '"ছাতাটি সাথে নাও"',
            question: 'ছাতাটি সাথে নাও',
            options: ['Take your umbrella', 'Wear your sunglasses', 'Drive slowly'],
            correctIndex: 0,
            speakerText: 'Take your umbrella',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u12_l2_e2',
            prompt: 'সাজান: "আজকের আবহাওয়া খুব সুন্দর"',
            sentenceToTranslate: 'আজকের আবহাওয়া খুব সুন্দর',
            correctSequence: ['The', 'weather', 'is', 'lovely', 'today'],
            tokenBank: ['The', 'weather', 'is', 'lovely', 'today', 'was', 'rain'],
            speakerText: 'The weather is lovely today',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u12_l2_e3',
            prompt: 'শূন্যস্থান পূরণ করুন:',
            prefix: 'The wind is blowing gently and the sky is ',
            blankAnswer: 'clear',
            suffix: '.',
            options: ['clear', 'cooked', 'pen'],
            speakerText: 'The wind is blowing gently and the sky is clear.',
          ),
        ],
      ),
    ],
  ),

  // ==========================================
  // LEVEL 4: UPPER-INTERMEDIATE (B2 • উচ্চ-মধ্যবর্তী স্তর)
  // ==========================================
  Unit(
    id: 'bn_en_u13',
    unitNumber: 13,
    title: 'অফিস, ক্যারিয়ার ও ইন্টারভিউ',
    description: 'চাকরির ইন্টারভিউ ও কর্পোরেট অফিসে প্রফেশনাল ইংরেজি বলা শিখুন',
    themeColor: const Color(0xFF1565C0), // Corporate Deep Blue
    levelTitle: 'LEVEL 4: UPPER-INTERMEDIATE (B2 • উচ্চ-মধ্যবর্তী স্তর)',
    levelBadge: 'B2',
    lessons: [
      Lesson(
        id: 'bn_en_u13_l1',
        title: 'চাকরির ইন্টারভিউ কৌশল',
        description: 'Tell me about yourself, Strengths, Experience',
        icon: Icons.badge_rounded,
        xpReward: 30,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u13_l1_e1',
            prompt: 'ইন্টারভিউয়ের শুরুতে নিজেকে কীভাবে পরিচয় দেবেন?',
            question: 'Tell me about yourself',
            options: [
              'I am a passionate professional with 3 years experience',
              'I have no idea what I am doing',
              'Can I go home now please',
            ],
            correctIndex: 0,
            speakerText: 'I am a passionate professional with three years experience',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u13_l1_e2',
            prompt: 'সাজান: "আমি খুব দ্রুত নতুন বিষয় শিখতে পারি"',
            sentenceToTranslate: 'আমি একজন দ্রুত শিক্ষার্থী',
            correctSequence: ['I', 'am', 'a', 'quick', 'learner'],
            tokenBank: ['I', 'am', 'a', 'quick', 'learner', 'slow', 'study', 'do'],
            speakerText: 'I am a quick learner',
          ),
          const SpeakingExercise(
            id: 'bn_en_u13_l1_e3',
            prompt: 'ইন্টারভিউতে স্পষ্ট করে বলুন:',
            targetPhrase: 'I look forward to contributing to your team',
            translation: 'আমি আপনাদের দলে অবদান রাখার জন্য উন্মুখ',
            targetWords: ['I', 'look', 'forward', 'to', 'contributing', 'to', 'your', 'team'],
            speakerText: 'I look forward to contributing to your team',
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u13_l2',
        title: 'অফিস মিটিং ও টিমওয়ার্ক',
        description: 'Meeting agenda, Deadline, Presentation, Collaboration',
        icon: Icons.groups_rounded,
        xpReward: 30,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u13_l2_e1',
            prompt: '"কাজের শেষ সময়সীমা কালকে" এর ইংরেজি কী?',
            question: 'শেষ সময়সীমা কালকে',
            options: ['The deadline is tomorrow', 'We are having lunch', 'The office is closed'],
            correctIndex: 0,
            speakerText: 'The deadline is tomorrow',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u13_l2_e2',
            prompt: 'সাজান: "চলুন একটি মিটিং শিডিউল করি"',
            sentenceToTranslate: 'চলুন একটি মিটিং ঠিক করি',
            correctSequence: ['Let', 'us', 'schedule', 'a', 'meeting'],
            tokenBank: ['Let', 'us', 'schedule', 'a', 'meeting', 'cancel', 'talk'],
            speakerText: 'Let us schedule a meeting',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u13_l2_e3',
            prompt: 'উপযুক্ত কর্পোরেট শব্দ বসান:',
            prefix: 'Effective communication is key to successful ',
            blankAnswer: 'teamwork',
            suffix: '.',
            options: ['teamwork', 'sleeping', 'shouting'],
            speakerText: 'Effective communication is key to successful teamwork.',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u14',
    unitNumber: 14,
    title: 'পেশাদার ইমেইল ও টেলিফোন',
    description: 'ফর্মাল ইমেইল লেখা ও টেলিফোনে প্রফেশনাল শিষ্টাচার পালন',
    themeColor: const Color(0xFF6A1B9A), // Royal Indigo
    lessons: [
      Lesson(
        id: 'bn_en_u14_l1',
        title: 'ফর্মাল ইমেইল লিখন',
        description: 'Dear Sir, Attached file, Sincerely, Best regards',
        icon: Icons.mark_email_read_rounded,
        xpReward: 30,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u14_l1_e1',
            prompt: 'ফর্মাল ইমেইল শেষ করার সেরা অভিবাদন কোনটি?',
            question: 'ফর্মাল ইমেইল সাইন-অফ',
            options: ['Best regards,', 'Bye bye!', 'See you soon'],
            correctIndex: 0,
            speakerText: 'Best regards',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u14_l1_e2',
            prompt: 'সাজান: "সংযুক্ত ফাইলটি অনুগ্রহ করে দেখুন"',
            sentenceToTranslate: 'সংযুক্ত ফাইলটি দেখুন',
            correctSequence: ['Please', 'find', 'the', 'attached', 'file'],
            tokenBank: ['Please', 'find', 'the', 'attached', 'file', 'send', 'lost'],
            speakerText: 'Please find the attached file',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u14_l1_e3',
            prompt: 'ইমেইল ফ্রেজগুলো মেলাও:',
            pairs: {
              'মহোদয়': 'Dear Sir / Madam',
              'শীঘ্রই জানানোর অনুরোধ': 'Looking forward to hearing from you',
              'আপনার অবগতির জন্য': 'For your information',
              'বিনীত': 'Sincerely yours',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u14_l2',
        title: 'টেলিফোনে কথা বলার শিষ্টাচার',
        description: 'Hold the line, Call back, May I speak to, Message',
        icon: Icons.ring_volume_rounded,
        xpReward: 30,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u14_l2_e1',
            prompt: '"একটু লাইনে থাকুন" ইংরেজিতে ভদ্রভাবে কী বলবেন?',
            question: 'একটু লাইনে থাকুন',
            options: ['Please hold the line', 'Hang up now', 'Do not talk'],
            correctIndex: 0,
            speakerText: 'Please hold the line',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u14_l2_e2',
            prompt: 'সাজান: "আমি কি মিস্টার স্মিথের সাথে কথা বলতে পারি?"',
            sentenceToTranslate: 'আমি কি কথা বলতে পারি?',
            correctSequence: ['May', 'I', 'speak', 'to', 'Mr', 'Smith?'],
            tokenBank: ['May', 'I', 'speak', 'to', 'Mr', 'Smith?', 'Can', 'tell'],
            speakerText: 'May I speak to Mr Smith?',
          ),
          const SpeakingExercise(
            id: 'bn_en_u14_l2_e3',
            prompt: 'ফোনে বলুন: "Thank you for calling, have a great day!"',
            targetPhrase: 'Thank you for calling have a great day',
            translation: 'কল করার জন্য ধন্যবাদ, আপনার দিনটি চমৎকার হোক!',
            targetWords: ['Thank', 'you', 'for', 'calling', 'have', 'a', 'great', 'day'],
            speakerText: 'Thank you for calling have a great day',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u15',
    unitNumber: 15,
    title: 'মতামত প্রকাশ ও গঠনমূলক আলোচনা',
    description: 'যুক্তি দেওয়া, একমত ও ভদ্রভাবে দ্বিমত পোষণ করা শিখুন',
    themeColor: const Color(0xFFEF6C00), // Burnt Orange
    lessons: [
      Lesson(
        id: 'bn_en_u15_l1',
        title: 'নিজের মতামত ব্যক্ত করা',
        description: 'In my opinion, I believe, Absolutely, I agree',
        icon: Icons.record_voice_over_rounded,
        xpReward: 30,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u15_l1_e1',
            prompt: '"আমার মতে" প্রকাশের সবচেয়ে প্রচলিত রূপ কোনটি?',
            question: 'আমার মতে',
            options: ['In my opinion,', 'In my sleep,', 'According to my shoes,'],
            correctIndex: 0,
            speakerText: 'In my opinion',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u15_l1_e2',
            prompt: 'সাজান: "আমি আপনার সাথে পুরোপুরি একমত"',
            sentenceToTranslate: 'আমি পুরোপুরি একমত',
            correctSequence: ['I', 'completely', 'agree', 'with', 'you'],
            tokenBank: ['I', 'completely', 'agree', 'with', 'you', 'disagree', 'no'],
            speakerText: 'I completely agree with you',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u15_l1_e3',
            prompt: 'মতামতের অভিব্যক্তি মেলাও:',
            pairs: {
              'নিঃসন্দেহে': 'Without a doubt',
              'আমার বিশ্বাস': 'I believe that',
              'একদম ঠিক': 'Exactly right',
              'আমার দৃষ্টিকোণ থেকে': 'From my perspective',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u15_l2',
        title: 'ভদ্রভাবে দ্বিমত পোষণ',
        description: 'I see your point, However, On the other hand',
        icon: Icons.balance_rounded,
        xpReward: 30,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u15_l2_e1',
            prompt: 'দ্বিমত পোষণের সবচেয়ে ভদ্র ও প্রফেশনাল পদ্ধতি কোনটি?',
            question: 'ভদ্রভাবে দ্বিমত পোষণ',
            options: [
              'I see your point, but I respectfully disagree',
              'You are totally wrong and bad',
              'Shut up please',
            ],
            correctIndex: 0,
            speakerText: 'I see your point but I respectfully disagree',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u15_l2_e2',
            prompt: 'সাজান: "আমরা কি অন্য কোনো উপায় বিবেচনা করতে পারি?"',
            sentenceToTranslate: 'অন্য উপায় বিবেচনা করা যাক',
            correctSequence: ['Could', 'we', 'consider', 'another', 'option?'],
            tokenBank: ['Could', 'we', 'consider', 'another', 'option?', 'must', 'take'],
            speakerText: 'Could we consider another option?',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u15_l2_e3',
            prompt: 'যুক্তির সংযোগ শব্দ বসান:',
            prefix: 'The plan is ambitious, ',
            blankAnswer: 'however',
            suffix: ' we need more budget to finish.',
            options: ['however', 'banana', 'run'],
            speakerText: 'The plan is ambitious however we need more budget to finish.',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u16',
    unitNumber: 16,
    title: 'বিমানবন্দর ও আন্তর্জাতিক ভ্রমণ',
    description: 'এয়ারপোর্ট বোর্ডিং, ইমিগ্রেশন ও বিদেশে হোটেল রিজার্ভেশন',
    themeColor: const Color(0xFF00838F), // Cyan Ocean
    lessons: [
      Lesson(
        id: 'bn_en_u16_l1',
        title: 'এয়ারপোর্ট ও ইমিগ্রেশন কাউন্টার',
        description: 'Boarding pass, Window seat, Purpose of visit',
        icon: Icons.flight_takeoff_rounded,
        xpReward: 30,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u16_l1_e1',
            prompt: 'ইমিগ্রেশন অফিসার জিজ্ঞেস করলেন: "What is the purpose of your visit?"',
            question: 'Purpose of your visit?',
            options: [
              'I am here for tourism and vacation',
              'I do not know why I am here',
              'Give me food please',
            ],
            correctIndex: 0,
            speakerText: 'I am here for tourism and vacation',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u16_l1_e2',
            prompt: 'সাজান: "আমি কি জানালার পাশের আসন পেতে পারি?"',
            sentenceToTranslate: 'জানালার পাশের আসন পাওয়া যাবে?',
            correctSequence: ['Could', 'I', 'have', 'a', 'window', 'seat?'],
            tokenBank: ['Could', 'I', 'have', 'a', 'window', 'seat?', 'door', 'car'],
            speakerText: 'Could I have a window seat?',
          ),
          const SpeakingExercise(
            id: 'bn_en_u16_l1_e3',
            prompt: 'বোর্ডিং কাউন্টারে বলুন:',
            targetPhrase: 'Here is my passport and boarding pass',
            translation: 'এই যে আমার পাসপোর্ট এবং বোর্ডিং পাস',
            targetWords: ['Here', 'is', 'my', 'passport', 'and', 'boarding', 'pass'],
            speakerText: 'Here is my passport and boarding pass',
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u16_l2',
        title: 'হোটেল চেক-ইন ও সার্ভিস',
        description: 'Reservation, Key card, Breakfast, Check-out',
        icon: Icons.hotel_rounded,
        xpReward: 30,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u16_l2_e1',
            prompt: '"আমার নামে একটি রুম বুকিং আছে"',
            question: 'রুম বুকিং আছে',
            options: [
              'I have a reservation under my name',
              'Where is my bedroom',
              'I will sleep in the lobby',
            ],
            correctIndex: 0,
            speakerText: 'I have a reservation under my name',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u16_l2_e2',
            prompt: 'সাজান: "নাস্তা কি ভাড়ার অন্তর্ভুক্ত?"',
            sentenceToTranslate: 'নাস্তা কি অন্তর্ভুক্ত?',
            correctSequence: ['Is', 'breakfast', 'included', 'in', 'the', 'price?'],
            tokenBank: ['Is', 'breakfast', 'included', 'in', 'the', 'price?', 'dinner', 'free'],
            speakerText: 'Is breakfast included in the price?',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u16_l2_e3',
            prompt: 'উপযুক্ত শব্দ বসান:',
            prefix: 'What time is ',
            blankAnswer: 'check-out',
            suffix: ' tomorrow morning?',
            options: ['check-out', 'lunch', 'running'],
            speakerText: 'What time is check-out tomorrow morning?',
          ),
        ],
      ),
    ],
  ),

  // ==========================================
  // LEVEL 5: ADVANCED & MASTERY (C1/C2 • উন্নত ও সাবলীল স্তর)
  // ==========================================
  Unit(
    id: 'bn_en_u17',
    unitNumber: 17,
    title: 'সেরা ইংরেজি বাগধারা ও ফ্রেজ',
    description: 'প্রবাদ-প্রবচন, Idioms ও Phrasal Verbs দিয়ে নেটিভদের মতো কথা বলুন',
    themeColor: const Color(0xFFC2185B), // Deep Rose
    levelTitle: 'LEVEL 5: ADVANCED & MASTERY (C1/C2 • উন্নত ও সাবলীল স্তর)',
    levelBadge: 'C1/C2',
    lessons: [
      Lesson(
        id: 'bn_en_u17_l1',
        title: 'জনপ্রিয় ইংরেজি Idioms',
        description: 'Piece of cake, Break a leg, Once in a blue moon',
        icon: Icons.psychology_rounded,
        xpReward: 35,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u17_l1_e1',
            prompt: '"A piece of cake" বাগধারাটির প্রকৃত অর্থ কী?',
            question: 'A piece of cake',
            options: [
              'খুবই সহজ বা অনায়াসসাধ্য কাজ (Very easy)',
              'একটি মিষ্টি কেকের টুকরা',
              'অনেক কঠিন সমস্যা',
            ],
            correctIndex: 0,
            speakerText: 'A piece of cake',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u17_l1_e2',
            prompt: 'সাজান: "পরীক্ষাটি আমার কাছে জলের মতো সহজ ছিল"',
            sentenceToTranslate: 'পরীক্ষাটি খুব সহজ ছিল',
            correctSequence: ['The', 'exam', 'was', 'a', 'piece', 'of', 'cake'],
            tokenBank: ['The', 'exam', 'was', 'a', 'piece', 'of', 'cake', 'hard', 'biscuit'],
            speakerText: 'The exam was a piece of cake',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u17_l1_e3',
            prompt: 'ইংরেজি বাগধারা ও ভাবার্থ মেলাও:',
            pairs: {
              'Break a leg': 'শুভকামনা (Good luck)',
              'Once in a blue moon': 'কদাচিৎ / খুব বিরল',
              'Hit the books': 'মনোযোগ দিয়ে পড়ালেখা করা',
              'Under the weather': 'সামান্য অসুস্থ বোধ করা',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u17_l2',
        title: 'নিত্যব্যবহৃত Phrasal Verbs',
        description: 'Give up, Figure out, Look forward to, Call off',
        icon: Icons.lightbulb_rounded,
        xpReward: 35,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u17_l2_e1',
            prompt: '"Never give up" কথাটির অর্থ কী?',
            question: 'Never give up',
            options: ['কখনও হাল ছেড়ো না', 'সব সময় ঘুমাও', 'দৌড়ে পালাও'],
            correctIndex: 0,
            speakerText: 'Never give up',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u17_l2_e2',
            prompt: 'সাজান: "আমি সমাধানটি বের করতে পেরেছি"',
            sentenceToTranslate: 'আমি সমাধানটি বের করেছি',
            correctSequence: ['I', 'figured', 'out', 'the', 'solution'],
            tokenBank: ['I', 'figured', 'out', 'the', 'solution', 'gave', 'lost', 'in'],
            speakerText: 'I figured out the solution',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u17_l2_e3',
            prompt: 'সঠিক Phrasal Verb বসান:',
            prefix: 'Due to heavy rainfall, they had to ',
            blankAnswer: 'call off',
            suffix: ' the outdoor cricket match.',
            options: ['call off', 'eat up', 'wake up'],
            speakerText: 'Due to heavy rainfall they had to call off the outdoor cricket match.',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u18',
    unitNumber: 18,
    title: 'সামাজিক শিষ্টাচার ও নেটওয়ার্কিং',
    description: 'অপরিচিতদের সাথে বন্ধুত্ব, স্মলটক ও আন্তর্জাতিক নেটওয়ার্কিং',
    themeColor: const Color(0xFF4527A0), // Deep Purple
    lessons: [
      Lesson(
        id: 'bn_en_u18_l1',
        title: 'আকর্ষণীয় স্মলটক ও আড্ডা',
        description: 'Break the ice, Great talking to you, Networking',
        icon: Icons.forum_rounded,
        xpReward: 35,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u18_l1_e1',
            prompt: 'কোনো আন্তর্জাতিক সম্মেলনে কারও পেশা জানতে কী বলবেন?',
            question: 'পেশা জানতে চাওয়া',
            options: [
              'What line of work are you in?',
              'Why do you have money?',
              'Give me your job please',
            ],
            correctIndex: 0,
            speakerText: 'What line of work are you in?',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u18_l1_e2',
            prompt: 'সাজান: "আপনার সাথে কথা বলে ভীষণ আনন্দ হলো"',
            sentenceToTranslate: 'কথা বলে খুব ভালো লাগলো',
            correctSequence: ['It', 'was', 'a', 'pleasure', 'talking', 'with', 'you'],
            tokenBank: ['It', 'was', 'a', 'pleasure', 'talking', 'with', 'you', 'bad', 'call'],
            speakerText: 'It was a pleasure talking with you',
          ),
          const SpeakingExercise(
            id: 'bn_en_u18_l1_e3',
            prompt: 'স্মলটকে সাবলীলভাবে বলুন:',
            targetPhrase: 'Let us stay in touch and connect on LinkedIn',
            translation: 'চলুন নিয়মিত যোগাযোগ রাখি এবং লিংকডইনে যুক্ত থাকি',
            targetWords: ['Let', 'us', 'stay', 'in', 'touch', 'and', 'connect', 'on', 'LinkedIn'],
            speakerText: 'Let us stay in touch and connect on LinkedIn',
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u18_l2',
        title: 'আন্তর্জাতিক সম্পর্ক ও বিদায়',
        description: 'Keep in touch, Safe travels, Wonderful experience',
        icon: Icons.handshake_rounded,
        xpReward: 35,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u18_l2_e1',
            prompt: 'ভ্রমণকারীকে আন্তরিক বিদায় জানাতে কোনটি বলবেন?',
            question: 'আন্তরিক বিদায়',
            options: [
              'Safe travels and wish you all the best!',
              'Do not come back ever',
              'The bus is noisy',
            ],
            correctIndex: 0,
            speakerText: 'Safe travels and wish you all the best',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u18_l2_e2',
            prompt: 'সাজান: "আমরা যোগাযোগ বজায় রাখব"',
            sentenceToTranslate: 'আমরা যোগাযোগ রাখব',
            correctSequence: ['We', 'will', 'definitely', 'keep', 'in', 'touch'],
            tokenBank: ['We', 'will', 'definitely', 'keep', 'in', 'touch', 'forget', 'never'],
            speakerText: 'We will definitely keep in touch',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u18_l2_e3',
            prompt: 'শূন্যস্থান পূরণ করুন:',
            prefix: 'Thank you for your gracious hospitality, it was a ',
            blankAnswer: 'memorable',
            suffix: ' visit.',
            options: ['memorable', 'cold', 'spicy'],
            speakerText: 'Thank you for your gracious hospitality, it was a memorable visit.',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u19',
    unitNumber: 19,
    title: 'জটিল শর্তযুক্ত বাক্য ও যুক্তি',
    description: 'Third Conditional, কাল্পনিক পরিস্থিতি ও যুক্তিশীল ইংরেজি গঠন',
    themeColor: const Color(0xFF2E7D32), // Emerald Green
    lessons: [
      Lesson(
        id: 'bn_en_u19_l1',
        title: 'উন্নত কন্ডিশনাল বাক্য',
        description: 'If I had known, Would have, Unless, Provided that',
        icon: Icons.account_tree_rounded,
        xpReward: 35,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u19_l1_e1',
            prompt: '"আগে জানলে আমি তোমাকে সাহায্য করতাম" - এর সঠিক ইংরেজি কোনটি?',
            question: 'আগে জানলে সাহায্য করতাম',
            options: [
              'If I had known, I would have helped you',
              'If I know, I will help you',
              'I helped you already yesterday',
            ],
            correctIndex: 0,
            speakerText: 'If I had known I would have helped you',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u19_l1_e2',
            prompt: 'সাজান: "নিয়মিত চর্চা না করলে তুমি উন্নতি করতে পারবে না"',
            sentenceToTranslate: 'চর্চা না করলে উন্নতি হবে না',
            correctSequence: ['Unless', 'you', 'practice,', 'you', 'cannot', 'improve'],
            tokenBank: ['Unless', 'you', 'practice,', 'you', 'cannot', 'improve', 'if', 'will'],
            speakerText: 'Unless you practice you cannot improve',
          ),
          const MatchingPairExercise(
            id: 'bn_en_u19_l1_e3',
            prompt: 'যুক্তিবাচক কানেক্টর মেলাও:',
            pairs: {
              'Although': 'যদিও',
              'Consequently': 'ফলস্বরূপ',
              'Furthermore': 'অধিকন্তু / এছাড়াও',
              'Provided that': 'শর্ত থাকে যে',
            },
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u19_l2',
        title: 'যুক্তি ও কার্যকারণ বিশ্লেষণ',
        description: 'Therefore, In addition, In contrast, Nonetheless',
        icon: Icons.analytics_rounded,
        xpReward: 35,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u19_l2_e1',
            prompt: 'দুটি বিপরীতমুখী ধারণাকে সুন্দরভাবে যুক্ত করতে কোনটি ব্যবহার করবেন?',
            question: 'বিপরীত ধারণা সংযোগ',
            options: ['On the other hand,', 'And and and', 'Because of this only'],
            correctIndex: 0,
            speakerText: 'On the other hand',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u19_l2_e2',
            prompt: 'সাজান: "কঠিন পরিস্থিতি সত্ত্বেও আমরা লক্ষ্য অর্জন করেছি"',
            sentenceToTranslate: 'আমরা লক্ষ্য অর্জন করেছি',
            correctSequence: ['Despite', 'the', 'challenges,', 'we', 'achieved', 'our', 'goal'],
            tokenBank: ['Despite', 'the', 'challenges,', 'we', 'achieved', 'our', 'goal', 'lost'],
            speakerText: 'Despite the challenges we achieved our goal',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u19_l2_e3',
            prompt: 'যুক্তিবোধক লিঙ্কার বসান:',
            prefix: 'The research was extensive; ',
            blankAnswer: 'therefore',
            suffix: ', the findings are highly reliable.',
            options: ['therefore', 'apple', 'running'],
            speakerText: 'The research was extensive therefore the findings are highly reliable.',
          ),
        ],
      ),
    ],
  ),

  Unit(
    id: 'bn_en_u20',
    unitNumber: 20,
    title: 'সাবলীল বক্তৃতা ও ইংরেজি মাস্টারি',
    description: 'মঞ্চে আত্মবিশ্বাসী ইংরেজি বক্তৃতা, প্রেজেন্টেশন ও চূড়ান্ত দক্ষতা অর্জন',
    themeColor: const Color(0xFFD84315), // Deep Amber Flame
    lessons: [
      Lesson(
        id: 'bn_en_u20_l1',
        title: 'পাবলিক স্পিকিং ও প্রেজেন্টেশন',
        description: 'Ladies and gentlemen, Key takeaway, Inspire, Convince',
        icon: Icons.campaign_rounded,
        xpReward: 40,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u20_l1_e1',
            prompt: 'একটি হৃদয়গ্রাহী আন্তর্জাতিক বক্তৃতার সূচনা কীভাবে করবেন?',
            question: 'বক্তৃতার চমৎকার সূচনা',
            options: [
              'Ladies and gentlemen, thank you for being here today',
              'I do not want to talk to anyone here',
              'Please give me money quickly',
            ],
            correctIndex: 0,
            speakerText: 'Ladies and gentlemen thank you for being here today',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u20_l1_e2',
            prompt: 'সাজান: "দৃঢ় সংকল্পের সাথে যেকোনো লক্ষ্য জয় করা সম্ভব"',
            sentenceToTranslate: 'যেকোনো লক্ষ্য অর্জন সম্ভব',
            correctSequence: ['Anything', 'is', 'possible', 'with', 'dedication', 'and', 'effort'],
            tokenBank: ['Anything', 'is', 'possible', 'with', 'dedication', 'and', 'effort', 'no'],
            speakerText: 'Anything is possible with dedication and effort',
          ),
          const SpeakingExercise(
            id: 'bn_en_u20_l1_e3',
            prompt: 'পূর্ণ আত্মবিশ্বাসের সাথে বলুন:',
            targetPhrase: 'I can now speak English fluently and confidently anywhere in the world',
            translation: 'আমি এখন বিশ্বের যেকোনো প্রান্তে সাবলীল ও আত্মবিশ্বাসের সাথে ইংরেজি বলতে পারি',
            targetWords: [
              'I', 'can', 'now', 'speak', 'English', 'fluently', 'and', 'confidently', 'anywhere', 'in', 'the', 'world'
            ],
            speakerText: 'I can now speak English fluently and confidently anywhere in the world',
          ),
        ],
      ),
      Lesson(
        id: 'bn_en_u20_l2',
        title: 'চূড়ান্ত ফ্লুয়েন্সি গ্র্যাজুয়েশন',
        description: 'Mastery, Global citizen, Fluency certificate, Congratulations',
        icon: Icons.military_tech_rounded,
        xpReward: 50,
        exercises: [
          const MultipleChoiceExercise(
            id: 'bn_en_u20_l2_e1',
            prompt: 'ইংরেজি ভাষা আয়ত্ত করার এই অনন্য যাত্রার চূড়ান্ত মাইলফলক:',
            question: 'Fluency Milestone',
            options: [
              'Congratulations! You have mastered English across all levels!',
              'You still need to restart from Unit 1',
              'English is not possible to learn',
            ],
            correctIndex: 0,
            speakerText: 'Congratulations! You have mastered English across all levels!',
          ),
          const SentenceBuilderExercise(
            id: 'bn_en_u20_l2_e2',
            prompt: 'সাজান: "জ্ঞান হলো সাফল্যের চূড়ান্ত চাবিকাঠি"',
            sentenceToTranslate: 'জ্ঞানই সাফল্যের চাবিকাঠি',
            correctSequence: ['Knowledge', 'is', 'the', 'key', 'to', 'success'],
            tokenBank: ['Knowledge', 'is', 'the', 'key', 'to', 'success', 'lock', 'car', 'door'],
            speakerText: 'Knowledge is the key to success',
          ),
          const FillInBlankExercise(
            id: 'bn_en_u20_l2_e3',
            prompt: 'চূড়ান্ত সাফল্যের শূন্যস্থান পূরণ করুন:',
            prefix: 'You are now an accomplished ',
            blankAnswer: 'fluent',
            suffix: ' English speaker ready for global opportunities!',
            options: ['fluent', 'sleeping', 'quiet'],
            speakerText: 'You are now an accomplished fluent English speaker ready for global opportunities!',
          ),
        ],
      ),
    ],
  ),
];
