// File generated by FlutterFire configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxivbWHJTfS-wxNkkrPZIzsyk0n4Ap7KU',
    appId: '1:614665764814:web:5f39113c5e3e516e06759f',
    messagingSenderId: '614665764814',
    projectId: 'lingofun-prod-1789373308',
    authDomain: 'lingofun-prod-1789373308.firebaseapp.com',
    storageBucket: 'lingofun-prod-1789373308.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYUZRdO9OOXDo3l3fFmAZcMLffocTJuW4',
    appId: '1:614665764814:android:65e1a600f4a179ee06759f',
    messagingSenderId: '614665764814',
    projectId: 'lingofun-prod-1789373308',
    storageBucket: 'lingofun-prod-1789373308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxcJTTfiFzspqICSYGMSLPgO7AhydWoq0',
    appId: '1:614665764814:ios:e335701dd75c152206759f',
    messagingSenderId: '614665764814',
    projectId: 'lingofun-prod-1789373308',
    storageBucket: 'lingofun-prod-1789373308.firebasestorage.app',
    iosClientId: '614665764814-sc8qhoub32tsrs5fo0euouj5513eh85m.apps.googleusercontent.com',
    iosBundleId: 'com.antigravity.lingoFun',
  );
}
